[phases.setup]
nixPkgs = ["python39", "gcc", "g++", "libgl1-mesa-glx", "libglib2.0-0"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Backend build completed'"]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT" 